<Project Sdk="Microsoft.NET.Sdk">

    <Sdk Name="Aspire.AppHost.Sdk" Version="13.0.0" />

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <UserSecretsId>80f702fe-7d0b-4922-97c5-98b5f606b617</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\AirportsService\AirportsService.csproj" />
        <ProjectReference Include="..\FlightsService\FlightsService.csproj" />
        <ProjectReference Include="..\GlobalSearchService\GlobalSearchService.csproj" />
        <ProjectReference Include="..\TechInterview.Web\TechInterview.Web.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.Hosting.AppHost" Version="13.4.6" />
        <PackageReference Include="Aspire.Hosting.Docker" Version="13.4.6" />
        <PackageReference Include="Aspire.Hosting.Redis" Version="13.4.6" />
    </ItemGroup>

</Project>
